### ISSUE TITLE
Question: OpenGL Core Profile in OS X

### ISSUE THREAD

**Issue by bsdooby** [IngwiePhoenix/FLTK#1]
Is it possible to get a "modern" OpenGL context (> 3) with FLTK in OS X? 
All I get is the default OpenGL 2.1 version (unusable for me). Thank you for a hint or two.

**Comment by IngwiePhoenix** [comment]
I am unfortunate, but I host FLTK as a mirror and do not use OpenGL with it myself.

You could extract the NSView and replace it with whatever you want and later swap it back at destruction time.

Fl_Window myWindow(...);
// Extract the Window, then the view.
NSWindow* myNSWindow = fl_xid(myWindow);

From here you can use the normal Cocoa API in order to replace the window view. I haven’t used Cocoa in a good forever myself, so I forgot most of the class methods.

If you need further support, please consider the mailing list at http://fltk.org <http://fltk.org/> . The people and devs are very friendly and often give very great suggestions. :)

Hope it helped!

**Comment by bsdooby** [comment]
I'll have a look at your suggestions. Thank you for your support!

**Comment by IngwiePhoenix** [comment]
Very welcome! :)
